### ISSUE TITLE
xmlsec-openssl: Impossible to build without pkg-config and with non-standard installation of dependent libraries

### ISSUE THREAD

**Issue by guneemwelloeux** [lsh123/xmlsec#131]
Hello,
Running Ubuntu 16.04, I have tried to compile xmlsec with openssl as a crypto backend library, but all my attempts have failed.
pkg-config is not installed, and I cannot use it in my situation, because my ultimate goal is to cross-compile Xmlsec, with non-system versions of its dependencies.

First tried `./configure --prefix=$PWD/INSTALLR --with-default-crypto=openssl`, which failed with the following error `checking for default crypto library... configure: error: 'openssl' is specified as default crypto library but it is not configured or found`

This is most probably due to libcrypto.a being installed in /usr/lib/x86_64-linux-gnu.

I then tried `./configure --prefix=$PWD/INSTALLR --with-default-crypto=openssl --with-openssl=/usr/lib/x86_64-linux-gnu`, which worked this time, but the make that followed failed, because the configure script set the wrong flags. Here is the make error: `gcc: error: /usr/lib/x86_64-linux-gnu/lib/libcrypto.a: No such file or directory`

The same error occurs even after setting properly the appropriate variables as follow:
`OPENSSL_CFLAGS=-I/usr/include
OPENSSL_LIBS=-L/usr/lib/x86_64-linux-gnu/`.

Note that I was able to solve the issue for LIBXML using the appropriate variables, and I believe this should also be possible for openssl.
Alternatively, my LDFLAGS and CPPFLAGS are always correctly set with the appropriate -L and -I options resp. but neither the configure script not make seem to care about it, which is very unfortunate.

Could you please have a look, and if possible make the necessary changes so that Xmlsec can be cross-compiled?

Thanks

**Comment by lsh123** [comment]
The right approach is to use --with-openssl=<dir> option. How does your openssl installation look like? The configs expect includes in <dir>/include/ and libs in <dir>/lib/ folders. For example, --with-openssl=/usr/local then OpenSSL includes should be in /usr/local/include/ and libs in /usr/local/lib/ folders respectively.

**Comment by guneemwelloeux** [comment]
That is what I understood. However, this assumption is not always true. On the latest Long Term Support version of Ubuntu (16.04), here is, according to my packages manager, the list of files installed, and their location (edited so that the post is not too long):

/usr/include/openssl/*.h
/usr/include/x86_64-linux-gnu/openssl/opensslconf.h
/usr/lib/x86_64-linux-gnu/libcrypto.a
/usr/lib/x86_64-linux-gnu/libcrypto.so
/usr/lib/x86_64-linux-gnu/libssl.a
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/pkgconfig/*.pc
/usr/share/doc/libssl-dev/changelog.Debian.gz
/usr/share/doc/libssl-dev/changelog.gz
/usr/share/doc/libssl-dev/copyright

You can see that the "includes in dir/include and libs in dir/lib" scheme is not valid on this rather popular operating system. In the same line of thought, if one needs to cross-compile, headers and libs could be in separate locations as well. Even worse, in some cases, configure would add -L/usr/lib64 options, causing the linking stage to fail, because some symbols from libc.so were missing; this is because the linker was using the system-wide libc.so instead of the one from my toolchain.

FYI, I finally managed to cross compile, after a great deat of no-so-great hacks and changes in configure.ac. I can share that if you feel it will be helpful.

**Comment by guneemwelloeux** [comment]
Doing some more testing today, the above assumption is not applicable to libxml and libxslt.
If I read configure.ac correctly, the values of --with-libxslt and --with-libxml are only used to "find" where {xml2,xslt}-config utilities are located, and then calls said utilities to find the lib.

In my case, the <location> provided to the --with-libxslt<location> option does not contain a bin folder, and therefore no xslt-config utility, so the one from $PATH (the system version) is used, leading to linking with the wrong library. The same goes for libxml, for which I get a configure error (because the system version is too ancient).

**Comment by petrovr** [comment]
Hi William and Aleksay,

In most case you will not get feedback if you use issue tracker. This is 
reason to send a copy of you request to mail list where you could reach 
more people and perhaps to find solution.

William OLLIVIER wrote:

> That is what I understood. However, this assumption is not always true. On the latest Long Term Support version of Ubuntu (16.04), here is, according to my packages manager, the list of files installed, and their location (edited so that the post is not too long):
So traditionally (since decades) --with-FOO-path${=VAL} mean package to 
use $VAL/include and $VAL/lib if VAL is specified. Otherwise option mean 
explicitly to enable feature FOO.

> /usr/include/openssl/*.h
> /usr/include/x86_64-linux-gnu/openssl/opensslconf.h
> [SNIP]
> /usr/lib/x86_64-linux-gnu/libcrypto.so
> [SNIP]

At some point of time an vendor decides to change locations of packages 
and design new scheme .../include/$PLATFORM/$FOO ../lib/$PLATFORM/$FOO. 
As result all packages that support --with-FOO-path can not be compiled 
easily. One of them is xmlsec.


For xmlsec cross-compilation I use pkg-config. As you don't want to use 
pkg-config I guess that you could mix
"Some influential environment variables" ( see ./configure --help) with 
option --with-openssl (note options without path argument).


Aleksay,
Configure script may not override environment variables listed in "Some 
influential environment variables". Please note description of those 
added by PKG_... macros, for instance:
   OPENSSL_CFLAGS               C compiler flags for OPENSSL, overriding 
pkg-config
   OPENSSL_LIBS                    linker flags for OPENSSL, overriding 
pkg-config

Macro like PKG_CHECK_MODULES(FOO, .... adds another macros 
AC_ARG_VAR(FOO_CFLAGS , ....) and AC_ARG_VAR(FOO_LIBS, .....).  Note 
that  description is "... overriding pkg-config" but variables are 
managed even build is without pkg-congig. For more details see for 
AC_ARG_VAR in autoconf manual .

Currently xmlsec configure script set OPENSSL_CFLAGS="" and 
OPENSSL_LIBS="" and after this is pkg-config check for openssl. This 
mean that users even can not override "pkg-config". This is defect.

Removing assignment like mentioned above will allow users not only 
override pkg-config, but to use those variables if build is without 
pkg-config.
Command grep '_LIBS=""' *.ac returns
LIBXSLT_LIBS=""
OPENSSL_LIBS=""
NSS_LIBS=""
GCRYPT_LIBS=""
GNUTLS_LIBS=""
MSCRYPTO_LIBS=""
XMLSEC_CRYPTO_LIBS=""
XMLSEC_DL_LIBS=""
and first six are mentioned in ./configure --help.  Same for CFLAGS.

For NSPR, as is not used in PKG... check-macro, you could explicitly add 
macros AC_ARG_VAR(NSPR_CFLAGS, .. and AC_ARG_VAR(NSPR_LIBS, ... .


William,
As work around you could set CC environment variable. For instance in 
one of my build environments CC is set as
CC="arm-linux-androideabi-gcc -march=armv7-a 
--sysroot=/opt/android/ndk/platforms/android-9/arch-arm -B.... -B...." 
where two -B options point to some non-standard(extra) locations.

Regards,
Roumen Petrov

**Comment by lsh123** [comment]
Roumen, thanks for explanation. This is a little more complex since the configure.ac script has logic for auto-detecting OpenSSL (and other packages) locations. I think I know how to fix it but it will take a couple days to do all the testing.

**Comment by guneemwelloeux** [comment]
Thank you both for looking into the issue and providing constructive feedback.
In all honesty, I have never used the autotools from a package maintainer's perspective, so I can't really be of much help here. However, after looking at it closer in the past couple of days, I can definitely tell it is not an easy thing, and I haven't yet found a definitive guide on how to do things right with autotools (if such a thing exists).

I did find a question on stackoverflow though, which I thought was interesting, in particular William Pursell's answer. Have a look here: https://stackoverflow.com/questions/10220946/pkg-check-modules-considered-harmful

@petrovr I will look into the CC trick you mention. In fact, I have already worked on 20 open source components, and setting the CFLAGS, CPPFLAGS and LD_FLAGS env vars was enough for the configure script to do the job.

@lsh123 Thanks for looking into a fix. I will be more than happy to test things on my side, with my very specific setup to make sure nothing was missed.

**Comment by lsh123** [comment]
@guneemwelloeux  Could you please try https://github.com/lsh123/xmlsec/pull/133 ?

You should specify OPENSSL_CFLAGS and OPENSSL_LIBS, plus --with-openssl

**Comment by lsh123** [comment]
Just to explain, the new model for detecting dependent libraries:

- Priority 0: Check if library is not needed (--without-xxx)
- Priority 1: (if supported) User specifies the path to source code (--with-xxx-src)
- Priority 2: User specifies path to installation  (--with-xxx)
- Priority 3: User sets both XXX_CFLAGS and XXX_LIBS flags
- Priority 4: Guess with pkg_config
- Priority 5: (if supported) Guess the config tool location (e.g. xml-config or xslt-config)
- Priority 6: (if supported) Guess using a list of folders (do not overwrite XXX_CFLAGS/XXX_LIBS flags).

**Comment by guneemwelloeux** [comment]
Looks much more sensible to me, will test as soon as I get to work, and let you know.

**Comment by lsh123** [comment]
Thanks for testing. Let me fix the "yes" issue. Meantime, can you try w/o --with-openssl / --with-libxml? Just set the OPENSSL_CFLAGS and OPENSSL_LIBS  and let it run?

**Comment by lsh123** [comment]
I fixed the "yes" folder error :) I believe it should work as described. Please re-open this issue or create a new one if you run into any problems on master.
