### ISSUE TITLE
Missing API to obtain the reason of xmldsig verification failure?..

### ISSUE THREAD

**Issue by ulidtko** [lsh123/xmlsec#157]
Hi!

Let's say that my app uses XML DSig, and needs to distinguish these cases:

 1) a signed xmldoc has valid signature;
 1) a signed xmldoc has invalid signature, *because document data and signature don't match*;
 1) a signed xmldoc has invalid signature, *because the certificate has expired*;
 1) a signed xmldoc has invalid signature, *because the certificate [chain] is not trusted*;
  ... etc.

By the available examples and the API reference documentation, I can see that 1. is easy: `xmlSecDSigCtx.status == xmlSecDSigStatusSucceeded`.

But I don't see any way to distinguish 2. 3. 4. ...
`xmlSecDSigStatus` has only three documented values: "succeeded", "invalid", and "unknown" (????).

What does `xmlSecDSigStatusUnknown` mean?

How do I get verification failure reason programmatically?

I know 100% that `libxmlsec` has that reason at some point or another, both as an int code and as a string message; because the `xmlsec1` CLI logs those.

Am I missing something? Please add an example, and explain what is `xmlSecDSigStatusUnknown`.

**Comment by lsh123** [comment]
1) The status of the digest match is returned in [xmlSecDSigReferenceCtx](https://www.aleksey.com/xmlsec/api/xmlsec-xmldsig.html#xmlSecDSigReferenceCtx) which is returned in [xmlSecDSigCtx](https://www.aleksey.com/xmlsec/api/xmlsec-xmldsig.html#xmlSecDSigCtx). Thus you can find out if the data didn't match. 

2) You can install your own error handler and intercept the error messages to get detailed reason. Not very reliable since will require error string matching.

3) I accept patches :)
