### ISSUE TITLE
Validation using X509 certificates with "not valid after" >= 2038 not working on 32-bit system with 32 bit time_t (using openssl)

### ISSUE THREAD

**Issue by robsan00** [lsh123/xmlsec#674]
I am trying to run xmlsec on a 32-bit device and am having issues validating an XML using X509 certificates using the xmlsec1 tool (I am trying to get this to run before I am using the API). As using exactly the same files on my 64-bit Linux host machine, I was debugging into the library and found out that the validation fails at https://github.com/lsh123/xmlsec/blob/master/src/openssl/x509.c#L1635.

The problem is that the certificate I am using is valid longer than 2038.  https://github.com/lsh123/xmlsec/blob/master/src/openssl/x509.c#L1461 tries to convert ASN1_TIME  to time_t which is bound to fail on a 32-bit device. Implementing my own tm to time_t converter won't help because, well, in the end it's still a 32-bit time_t.

Updating to 64-bit time_t is sadly no option as I am bound to an older 32-bit powerpc platform which isn't supported by newer glibc versions that contain the necessary 64-bit time_t.

Do you have got any suggestions on how to procede here? Patching (forking) xmlsec to use a 64-bit time format would prevent me from future security updates (or at least it would heavily increase the effort).

**Comment by lsh123** [comment]
Hm... So I think the right way to handle it is to define XMLSEC_TIME_T typedef (with time_t as default) and enable a configure flag to use switch to int64 or double. Then use XMLSEC_TIME_T for all notValidBefore/notValidAfter and change all the related functions to handle non-time_t types correctly. This will ensure backward binary API compatibility.

Unfortunately this is non-trivial change and I don't know when I will get to it (in particular, the issue is that this change impacts not just xmlsec-openssl but all other crypto libraries as well). However if you have time and can do a PR for openssl then it will definitely help.

**Comment by robsan00** [comment]
Thanks for the quick response. In the end, I went for a temporary (?) hack (in the tm -> time_t conversion in my_timegm in src/openssl/x509.c, if the tm is such that an overflow would occur, I return time_t max; as far as I have seen in the code, this should not break anything for the time being). We will investigate getting glibc updated for our platform because otherwise our system would be f-ed at a lot of places in 2038.
